WUNDERLIST_CLIENT_ID="__INSERT_YOURS_HERE__" \
WUNDERLIST_CLIENT_SECRET="__INSERT_YOURS_HERE__" \
WUNDERLIST_USER_TOKEN="__INSERT_YOURS_HERE__" \
SENDGRID_API_KEY="__INSERT_YOURS_HERE__" \
EMAIL_FROM="__INSERT_YOURS_HERE__" \
EMAIL_TO="__INSERT_YOURS_HERE__" \
node run.js $@
