FIREBASE_API_KEY="__INSERT_YOURS_HERE__" \
FIREBASE_DATA_URL="https://__INSERT_YOURS_HERE__.firebaseio.com" \
FIREBASE_DATA_PATH="/__INSERT_YOURS_HERE__" \
SENDGRID_API_KEY="__INSERT_YOURS_HERE__" \
EMAIL_FROM="__INSERT_YOURS_HERE__" \
EMAIL_TO="__INSERT_YOURS_HERE__" \
node run.js $@
